# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - release  
    tags:
      - 'v*'
      - 'augus-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}